# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  # Expose ports to the host.
  config.vm.network "forwarded_port", guest: 4646, host: 4646, host_ip: "127.0.0.1" # Nomad HTTP API/UI
  config.vm.network "forwarded_port", guest: 8500, host: 8500, host_ip: "127.0.0.1" # Consul HTTP API/UI
  config.vm.network "forwarded_port", guest: 9090, host: 9090, host_ip: "127.0.0.1" # Prometheus HTTP API/UI

  # Share current directory with jobs and configuration files with the VM. Add
  # the shared files in a sub-dir.
  config.vm.synced_folder "./", "/home/vagrant/nomad-autoscaler"
  config.vm.synced_folder "../shared", "/home/vagrant/nomad-autoscaler-shared"

  # VM configuration.
  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "modifyvm", :id, "--uartmode1", "file", File::NULL ]
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Provision demo dependencies.
  #   - Downloads and install Nomad, Consul and Docker
  # Only runs when the VM is created.
  config.vm.provision "deps", type: "shell", inline: <<-SHELL

    # Install dependencies.
    apt-get update
    apt-get install -y \
      apt-transport-https \
      ca-certificates \
      curl \
      jq \
      software-properties-common

    # Download and install Docker.
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/docker.gpg
    echo "deb [signed-by=/usr/share/keyrings/docker.gpg arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt-get install -y \
      docker-ce \
      docker-ce-cli \
      containerd.io
    docker run hello-world
    usermod -aG docker vagrant

    # Download and install Nomad and Consul.
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/hashicorp.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp.gpg arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list > /dev/null
    apt-get update
    apt-get install -y \
      nomad \
      consul
  SHELL

  # Setup demo dependencies.
  #   - Create daemons for Nomad and Consul
  # Runs everytime the VM starts.
  config.vm.provision "app:setup", type: "shell", run: "always", inline: <<-SHELL
    # Copy across the config files.
    cp /home/vagrant/nomad-autoscaler-shared/consul.hcl /etc/consul.d/
    cp /home/vagrant/nomad-autoscaler/files/nomad.hcl /etc/nomad.d/

    # Enable and start the daemons
    systemctl enable consul
    systemctl start consul
    sudo systemctl enable nomad
    sudo systemctl start nomad
  SHELL

end
