{
 "title": "Demo",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Webapp Instances / Open Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nomad_nomad_job_summary_running{task_group=\"demo\"}",
     "legendFormat": "running_allocs_demo"
    },
    {
     "expr": "sum(traefik_entrypoint_open_connections{entrypoint=\"webapp\"} / scalar(nomad_nomad_job_summary_running{task_group=\"demo\"}))",
     "legendFormat": "current_connections"
    }
   ]
  },
  {
   "title": "Webapp Response Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(code) (rate(traefik_entrypoint_requests_total{entrypoint=\"webapp\"}[30s]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "HashiStack Client Unallocated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nomad_client_unallocated_cpu{node_class=\"hashistack\"} * 100 / (nomad_client_unallocated_cpu{node_class=\"hashistack\"} + nomad_client_allocated_cpu{node_class=\"hashistack\"})) / count(nomad_client_unallocated_cpu)",
     "legendFormat": "unallocated_cpu_hashistack"
    },
    {
     "expr": "sum(nomad_client_unallocated_memory{node_class=\"hashistack\"} * 100 / (nomad_client_unallocated_memory{node_class=\"hashistack\"} + nomad_client_allocated_memory{node_class=\"hashistack\"})) / count(nomad_client_unallocated_memory)",
     "legendFormat": "unallocated_mem_hashistack"
    }
   ]
  },
  {
   "title": "Hashistack Running Clients",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(nomad_client_unallocated_cpu)"
    }
   ]
  },
  {
   "title": "HashiStack Client CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nomad_client_host_cpu_total{node_class=\"hashistack\"}",
     "legendFormat": "{{node_class}}_{{cpu}}"
    }
   ]
  },
  {
   "title": "HashiStack Client Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nomad_client_host_memory_used{node_class=\"hashistack\"}"
    }
   ]
  },
  {
   "title": "Hashistack Total Resources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nomad_client_allocated_cpu{node_class=\"hashistack\"} +  nomad_client_unallocated_cpu{node_class=\"hashistack\"})",
     "legendFormat": "hashistack_available_cpu"
    },
    {
     "expr": "sum(nomad_client_allocated_memory{node_class=\"hashistack\"} +  nomad_client_unallocated_memory{node_class=\"hashistack\"})",
     "legendFormat": "hashistack_available_memory"
    }
   ]
  }
 ]
}